name: GitHub Actions Demo
on: 
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  Build-GitOps-app:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
        echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
        echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - uses: actions/setup-node@v3
        name: Set up Node.js
        with:
          node-version: 16

      #- name: Installing necessary tools - Node.js
      #  run: |
      #    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
      #    sudo apt-get install -y nodejs
      #    apt-get install -y build-essential
      #    node -v
      #    npm -v

      - name: Installing necessary tools - Terser
        run: |
          npm install terser -g

      - name: Run JS compressor
        run: |
          cd ${{ github.workspace }}
          terser --compress --mangle --output app-compressed.js -- app.js
          mv -f app-compressed.js app.js

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gitops-test:latest

      - run: echo "🍏 This job's status is ${{ job.status }}."
